name: urbun_guide
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_dart: ^1.2.1
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  firebase_storage: ^12.3.3
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.8
  random_string: ^2.3.1
  iconsax: ^0.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launch_icon.png"
  adaptive_icon_background: "#D0F2FD"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/logo.png
    - assets/images/man.png
    - assets/placeholder_avatar.png
    - assets/rainy.png
    - assets/
